### ISSUE TITLE
Success checking in 05_spirvkernelfromfile

### ISSUE THREAD

**Issue by maxaehle** [bashbaug/SimpleOpenCLSamples#42] opened 2021-08-10 15:00 UTC
First of all, thank you very much for these OpenCL reference examples! I have a question/feature request regarding the `05_spirvkernelfromfile` sample.

## Output of the code
On my system, I get the following output of the `05_spirvkernelfromfile` example and without command-line arguments:

    Running on platform: Intel Gen OCL Driver
    Running on device: Intel(R) HD Graphics Haswell GT2 Mobile
    CL_DEVICE_ADDRESS_BITS is 32 for this device.
    Reading SPIR-V from file: sample_kernel64.spv
    Building program with build options: (none)
    Creating kernel: Test
    Done.

i.e. the program pretends a successful run. Actually it failed however, which I noticed in two ways:

## Way 1: Output the results.
For this, replace the line `commandQueue.finish();` by

     const cl_uint*  pDst = (const cl_uint*)commandQueue.enqueueMapBuffer(
            deviceMemDst,
            CL_TRUE,
            CL_MAP_READ,
            0,
            gwx * sizeof(cl_uint) );
    commandQueue.finish();
    for(int i=0; i<gwx; i++){
        printf(" %d", pDst[i]);
    }
(adapted from sample `01_copybuffer`). On my system this prints unpredictable numbers. For an analogous modification of the sample `05_kernelfromfile`, I get the expected output `0 1 2 3 ...`.

## Way 2: Enable OpenCL exceptions.
Adding `#define CL_HPP_ENABLE_EXCEPTIONS` before `#include <CL/opencl.hpp>`, I get the output

       ....
        Building program with build options: (none)
        terminate called after throwing an instance of 'cl::Error'
         what():  clGetProgramInfo
        Aborted (core dumped)

The `SIGABRT` is received in the following line: `program.build(buildOptions.c_str());` according to gdb. In the sample `05_kernelfromfile`, no exception is raised.

## My system
See the above output and the output of `clinfo`:
```
Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short
  Platform Extensions function suffix             Intel

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 1
  Device Name                                     Intel(R) HD Graphics Haswell GT2 Mobile
  Device Vendor                                   Intel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 beignet 1.3
  Driver Version                                  1.3
  Device OpenCL C Version                         OpenCL C 1.2 beignet 1.3
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               20
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None, None, None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             512x512x512
  Max work group size                             512
  Preferred work group size multiple (kernel)     16
  Preferred / native vector sizes
    char                                                16 / 8
    short                                                8 / 8
    int                                                  4 / 4
    long                                                 2 / 2
    half                                                 0 / 8        (n/a)
    float                                                4 / 4
    double                                               0 / 2        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           1610612736 (1.5GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        8192 (8KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   4096 bytes
    Pitch alignment for 2D image buffers          1 pixels
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             8192x8192x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Max number of constant args                     8
  Max constant buffer size                        134217728 (128MiB)
  Max size of kernel argument                     1024
  Queue properties
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      80ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
```                                                                                                           
I compiled the example like this:

    clang -c -cl-std=CL1.2 -target spir64 -emit-llvm -Xclang -finclude-default-header -O3 sample_kernel.cl -o sample_kernel64.ll
    llvm-spirv sample_kernel64.ll -o sample_kernel64.spv

    clang -c -cl-std=CL1.2 -target spir -emit-llvm -Xclang -finclude-default-header -O3 sample_kernel.cl -o sample_kernel32.ll
    llvm-spirv sample_kernel32.ll -o sample_kernel32.spv

    clang++ -g main.cpp -lOpenCL -I.

with `clang`, `clang++` and `llvm-spirv` version 11.0.1, and latest `popl.hpp`.

## Requests
- Could you please try to reproduce the reported behavior in the `05_spirvkernelfromfile` sample?
- If not, do you know what I'm doing wrong?
- Could you add a verification of the output for the sample and/or add the `CL_HPP_ENABLE_EXCEPTIONS` symbol, such that users of the code can quickly notice if loading a SPIR-V kernel fails?

**Comment by bashbaug** [comment] 2021-08-10 23:51
Hi @maxaehle, thank you for a very comprehensive issue description - much appreciated!

I don't have easy access to a Haswell system for testing so I haven't been able to reproduce your results but I think I know what is happening: In short, your drivers don't support SPIR-V because they don't support OpenCL 2.1 or newer or the `cl_khr_il_program` extension.  You aren't doing anything wrong, but unfortunately this means that you are not going to be able to run the "spirvkernelfromfile" sample on your Haswell GPU.  You may be able to execute this sample on a CPU OpenCL device.

I'm open to suggestions to make this sample more robust, though I do want to balance sample length and readability against robustness.  Some options to consider (these are not mutually exclusive):

1. I can add checks for SPIR-V support and print an error message if SPIR-V isn't supported.
2. I can print the first few values in the output buffer as you've suggested.  I don't do this in any of the samples in the master branch currently, but I do this in [a few other samples](https://github.com/bashbaug/SimpleOpenCLSamples/blob/specconst/samples/99_specconst/main.cpp#L241).
3. I can add a CMake option to define `CL_HPP_ENABLE_EXCEPTIONS` if desired, though it'll probably be disabled by default.

Should I add all of these?

I'd also strongly recommend checking out the [OpenCL Intercept Layer](https://github.com/intel/opencl-intercept-layer) if you haven't already.  It's a great way to debug and analyze problems like these - have a look at the [CallLogging](https://github.com/intel/opencl-intercept-layer/blob/master/docs/controls.md#calllogging-bool) and [ErrorLogging](https://github.com/intel/opencl-intercept-layer/blob/master/docs/controls.md#errorlogging-bool) controls specifically.

Thanks!

**Comment by maxaehle** [comment] 2021-08-11 12:21
Thanks @bashbaug for your quick reply!

As you hinted, I am able to run the sample successfully on an `Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz` OpenCL device via the `Intel(R) CPU Runtime for OpenCL(TM) Applications`. That's what I need at the moment, thanks again!

I think I would find all three options useful ;-) - as an OpenCL newbie, because I'm not only interested in how things are done on a working system, but also in whether things function on my particular system at all. Instead of printing (a part of) the output buffer, one could verify its content and print an error message otherwise, as you did in the `01_copybuffer` sample. I'm leaving the issue open in case you decide to apply some of the options.

**Comment by bashbaug** [comment] 2021-08-11 20:30
> I'm leaving the issue open in case you decide to apply some of the options.

Thanks, sounds good, I'll try to get these added in the next couple of days.

**Comment by bashbaug** [comment] 2021-08-13 15:32
Just FYI, no action required, I think I've implemented all of the suggestions above, see: https://github.com/bashbaug/SimpleOpenCLSamples/pull/43

I'll merge this shortly.

Thank you for the suggestions, I think this is a nice improvement!

**Comment by bashbaug** [comment] 2021-09-30 04:33
I think everything from this issue is resolved.  Closing!

**Closed by bashbaug** 2021-09-30 04:33 UTC
